var gods = 
[ 
    ["Achilles","achilles","Warrior", "warrior", "physical"], 
    ["Agni","agni","Mage", "mage", "magical"], 
    ["Ah Muzen Cab","ahmuzencab","Hunter", "hunter", "physical"], 
    ["Ah Puch","ahpuch","Mage", "mage", "magical"], 
    ["Anhur","anhur","Hunter", "hunter", "physical"], 
    ["Amaterasu","amaterasu","Warrior", "warrior", "physical"], 
    ["Anubis","anubis","Mage", "mage", "magical"], 
    ["Ao Kuang","aokuang","Mage", "mage", "magical"], 
    ["Aphrodite","aphrodite","Mage", "mage", "magical"], 
    ["Apollo","apollo","Hunter", "hunter", "physical"], 
    ["Arachne","arachne","Assassin", "assassin", "physical"], 
    ["Ares","ares","Guardian", "guardian", "magical"], 
    ["Artemis","artemis","Hunter", "hunter", "physical"], 
    ["Artio","artio","Guardian", "guardian", "magical"], 
    ["Athena","athena","Guardian", "guardian", "magical"], 
    ["Awilix","awilix","Assassin", "assassin", "physical"], 
    ["Bacchus","bacchus","Guardian", "guardian", "magical"], 
    ["Bakasura","bakasura","Assassin", "assassin", "physical"], 
    ["Baron Samedi","baronsamedi","Mage", "mage", "magical"], 
    ["Bastet","bastet","Assassin", "assassin", "physical"], 
    ["Bellona","bellona","Warrior", "warrior", "physical"], 
    ["Cabrakan","cabrakan","Guardian", "guardian", "magical"], 
    ["Camazotz","camazotz","Assassin", "assassin", "physical"], 
    ["Cernunnos","cernunnos","Hunter", "hunter", "physical"], 
    ["Cerberus","cerberus","Guardian", "guardian", "magical"], 
    ["Chaac","chaac","Warrior", "warrior", "physical"], 
    ["Chang'e","change","Mage", "mage", "magical"], 
    ["Chernabog","chernabog","Hunter", "hunter", "physical"], 
    ["Chiron","chiron","Hunter", "hunter", "physical"], 
    ["Chronos","chronos","Mage", "mage", "magical"], 
    ["Cu Chulainn","cuchulainn","Warrior", "warrior", "physical"], 
    ["Cupid","cupid","Hunter", "hunter", "physical"], 
    ["Da Ji","daji","Assassin", "assassin", "physical"], 
    ["Discordia","discordia","Mage", "mage", "magical"], 
    ["Erlang Shen","erlangshen","Warrior", "warrior", "physical"], 
    ["Fafnir","fafnir","Guardian", "guardian", "magical"], 
    ["Fenrir","fenrir","Assassin", "assassin", "physical"], 
    ["Freya","freya","Mage", "mage", "magical"], 
    ["Ganesha","ganesha","Guardian", "guardian", "magical"], 
    ["Geb","geb","Guardian", "guardian", "magical"], 
    ["Guan Yu","guanyu","Warrior", "warrior", "physical"], 
    ["Hachiman","hachiman","Hunter", "hunter", "physical"], 
    ["Hades","hades","Mage", "mage", "magical"], 
    ["He Bo","hebo","Mage", "mage", "magical"], 
    ["Heimdallr","heimdallr","Hunter", "hunter", "physical"],
    ["Hel","hel","Mage", "mage", "magical"], 
    ["Hera","hera","Mage", "mage", "magical"], 
    ["Hercules","hercules","Warrior", "warrior", "physical"], 
    ["Horus","horus","Warrior", "warrior", "physical"], 
    ["Hou Yi","houyi","Hunter", "hunter", "physical"], 
    ["Hun Batz","hunbatz","Assassin", "assassin", "physical"], 
    ["Isis","isis","Mage", "mage", "magical"], 
    ["Izanami","izanami","Hunter", "hunter", "physical"], 
    ["Janus","janus","Mage", "mage", "magical"], 
    ["Jing Wei","jingwei","Hunter", "hunter", "physical"], 
    ["Jormungandr","jormungandr","Guardian", "guardian", "magical"], 
    ["Kali","kali","Assassin", "assassin", "physical"], 
    ["Khepri","khepri","Guardian", "guardian", "magical"], 
    ["King Arthur","kingarthur","Warrior", "warrior", "physical"], 
    ["Kukulkan","kukulkan","Mage", "mage", "magical"], 
    ["Kumbhakarna","kumbakharna","Guardian", "guardian", "magical"], 
    ["Kuzenbo","kuzenbo","Guardian", "guardian", "magical"],     
    ["Loki","loki","Assassin", "assassin", "physical"], 
    ["Medusa","medusa","Hunter", "hunter", "physical"], 
    ["Mercury","mercury","Assassin", "assassin", "physical"], 
    ["Merlin","merlin","Mage", "mage", "magical"], 
    ["Neith","neith","Hunter", "hunter", "physical"], 
    ["Nemesis","nemesis","Assassin", "assassin", "physical"], 
    ["Ne Zha","nezha","Assassin", "assassin", "physical"], 
    ["Nike","nike","Warrior", "warrior", "physical"], 
    ["Nox","nox","Mage", "mage", "magical"], 
    ["Nu Wa","nuwa","Mage", "mage", "magical"], 
    ["Odin","odin","Warrior", "warrior", "physical"], 
    ["Olorun","olorun","Mage", "mage", "magical"], 
    ["Osiris","osiris","Warrior", "warrior", "physical"], 
    ["Pele","pele","Assassin", "assassin", "physical"], 
    ["Persephone","persephone","Mage", "mage", "magical"], 
    ["Poseidon","poseidon","Mage", "mage", "magical"], 
    ["Ra","ra","Mage", "mage", "magical"], 
    ["Raijin","raijin","Mage", "mage", "magical"], 
    ["Rama","rama","Hunter", "hunter", "physical"], 
    ["Ratatoskr","ratatoskr","Assassin", "assassin", "physical"], 
    ["Ravana","ravana","Assassin", "assassin", "physical"], 
    ["Scylla","scylla","Mage", "mage", "magical"], 
    ["Serqet","serqet","Assassin", "assassin", "physical"], 
    ["Set","set","Assassin", "assassin", "physical"], 
    ["Skadi","skadi","Hunter", "hunter", "physical"], 
    ["Sobek","sobek","Guardian", "guardian", "magical"], 
    ["Sol","sol","Mage", "mage", "magical"], 
    ["Sun Wukong","sunwukong","Warrior", "warrior", "physical"], 
    ["Susano","susano","Assassin", "assassin", "physical"], 
    ["Sylvanus","sylvanus","Guardian", "guardian", "magical"], 
    ["Terra","terra","Guardian", "guardian", "magical"], 
    ["Thanatos","thanatos","Assassin", "assassin", "physical"], 
    ["The Morrigan","themorrigan","Mage", "mage", "magical"], 
    ["Thor","thor","Assassin", "assassin", "physical"], 
    ["Thoth","thoth","Mage", "mage", "magical"], 
    ["Tyr","tyr","Warrior", "warrior", "physical"], 
    ["Ullr","ullr","Hunter", "hunter", "physical"], 
    ["Vamana","vamana","Warrior", "warrior", "physical"], 
    ["Vulcan","vulcan","Mage", "mage", "magical"], 
    ["Xbalanque","xbalanque","Hunter", "hunter", "physical"], 
    ["Xing Tian","xingtian","Guardian", "guardian", "magical"], 
    ["Yemoja","yemoja","Guardian", "guardian", "magical"], 
    ["Ymir","ymir","Guardian", "guardian", "magical"], 
    ["Zeus","zeus","Mage", "mage", "magical"], 
    ["Zhong Kui","zhongqui","Mage", "mage", "magical"] 
];